import prod1 from './../assets/prodImg.png'
const PRODUCTS = [
  {
    id: 1,
    name: "Мужские Кроссовки Under Armour Curry 8",
    preview:'https://zenden.ru/upload/iblock/0bb/0bb21b44e7768e7407a1ed8225f8c778.jpg',
    price:13999,
  },
  {
    id: 2,
    name: " Кроссовки Крутые",
    preview:prod1,
    price:13999,
  },
  {
    id: 3,
    name: "Мужские Кроссовки Under Armour Curry 8",
    preview:'https://zenden.ru/upload/iblock/0bb/0bb21b44e7768e7407a1ed8225f8c778.jpg',
    price:13999,
  },
  {
    id: 4,
    name: "Мужские Кроссовки Under Armour Curry 8",
    preview:prod1,
    price:13999,
  },
  {
    id: 5,
    name: "Мужские Кроссовки Under Armour Curry 8",
    preview:'https://zenden.ru/upload/iblock/0bb/0bb21b44e7768e7407a1ed8225f8c778.jpg',
    price:13999,
  },
  {
    id: 6,
    name: "Мужские Кроссовки Under Armour Curry 8",
    preview:prod1,
    price:13999,
  },
];

export default PRODUCTS;
