import banner from "./../assets/banner.png";
const SLIDES = [
  {
    id: 1,
    background: "#f4efe9",
    url: banner,
    text: "New shoes",
    button: {
      url: "/",
      text: "Приобрести",
    },
  },
  {
    id: 2,
    background: "#fff",
    url: 'https://myreact.ru/wp-content/uploads/2021/09/14650682_23030794_1000-10.jpg',
    text: "Vans",
    button: {
      url: "/",
      text: "Купить",
    },
  },
  {
    id: 3,
    background: "#fff",
    url: 'https://img2.traektoria.ru/upload/trk_iblock_img/ee4/a6c13c4c9bw43g4jfg7om57x23z4mby4.jpg',
    text: "Vans",
    button: {
      url: "/",
      text: "Купить",
    },
  },
];

export default SLIDES;
